version: 2

models:
  - name: tops_order_customer
    columns:
      - name: O_ORDERKEY
        description: "This is unique value for order table"
        tests:
          - unique
          - not_null
